<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ManimPilot.Core\ManimPilot.Core.csproj" />
    <ProjectReference Include="..\ManimPilot.Audio\ManimPilot.Audio.csproj" />
  </ItemGroup>

</Project>
